const CONGITO_USER_POOL_ID = import.meta.env.VITE_CONGITO_USER_POOL_ID
const CONGITO_USER_POOL_WEB_CLIENT_ID = import.meta.env
  .VITE_CONGITO_USER_POOL_WEB_CLIENT_ID

export { CONGITO_USER_POOL_ID, CONGITO_USER_POOL_WEB_CLIENT_ID }
